server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
#  profiles:
#    active: dev
  datasource:
      username: root
      password: root1234
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6379
#    password: 123
#
#mybatis:
#  type-aliases-package: com.inshare.demo.entity
#  mapper-locations: classpath:mapper/*.xml
#
#mapper:
#  not-empty: false
#  identity: MYSQL
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

